;**************************************************************************
; SBM 2017. ESTRUCTURA BÁSICA DE UN PROGRAMA EN ENSAMBLADOR
;**************************************************************************
; DEFINICION DEL SEGMENTO DE DATOS
DATOS SEGMENT
NUMERO DB 17 ;; Numero de elementos a captrurar.
ALMACENADO DB ?;;
FILA1 DB 4,3,1,2 ;; Primera fila de la matriz
FILA2 DB 1,2,4,3 ;; Segunda fila de la matriz
FILA3 DB 3,1,2,4 ;; Tercera fila de la matriz
FILA4 DB 2,4,3,1 ;; Cuarta fila de la matriz
CONVERSION DB ?
MENSAJE DB  "INTRODUZCA LAS FILAS DE LA MATRIZ(4)",13,10,'$'
FILASOK DB  "Filas validas [SI].",'$'
COLUMNASERR DB  "Columnas validas [NO]",13,10,'$'
FILASERR DB  "Filas validas [NO].",'$'
COLUMNASOK DB  "Columnas validas [SI]",13,10,'$'
ESPACIO DB 13,10,'$'
;-- rellenar con los datos solicitados
DATOS ENDS
;**************************************************************************
; DEFINICION DEL SEGMENTO DE PILA
PILA SEGMENT STACK "STACK"
DB 40H DUP (0) ;ejemplo de inicialización, 64 bytes inicializados a 0
PILA ENDS
;**************************************************************************
; DEFINICION DEL SEGMENTO EXTRA
EXTRA SEGMENT
RESULT DW 0,0 ;ejemplo de inicialización. 2 PALABRAS (4 BYTES)
EXTRA ENDS
;**************************************************************************
; DEFINICION DEL SEGMENTO DE CODIGO
CODE SEGMENT
ASSUME CS: CODE, DS: DATOS, ES: EXTRA, SS: PILA
; COMIENZO DEL PROCEDIMIENTO PRINCIPAL
INICIO PROC
; INICIALIZA LOS REGISTROS DE SEGMENTO CON SU VALOR
MOV AX, DATOS
MOV DS, AX
MOV AX, PILA
MOV SS, AX
MOV AX, EXTRA
MOV ES, AX
MOV SP, 64 ; CARGA EL PUNTERO DE PILA CON EL VALOR MAS ALTO
; FIN DE LAS INICIALIZACIONES
; COMIENZO DEL PROGRAMA
CALL CAPTURAMATRIZ
;;CAPTURAMOS EL NUEVO VECTOR

MOV CX, 0
;;PROCESO DE IMPRESION DEL VECTOR
PROCESO:
	ADD CX, 4 ;;INICIAMOS CX EN EL SIGUIENTE VECTOR 
	;;;;;;;IMPRIMIMOS LOS CORCHETES;;;;;;;;;;;;;;;;;;;
	mov AH, 2 ; Número de función = 2
	mov DL, '|' ; Se desea imprimir la letra A
	int 21h ; Interrupción software al sistema operativo 
	MOV DI, CX ;;INICIALIZAMOS DI INDICE DEL VECTOR A 0 (RESPECTO AL VECTOR QUE MIRAMOS)
	SUB DI, 4
	;;;;;;;IMPRIMIMOS EL VECTOR;;;;;;;;;;;;;;;;;;;
	COMIENZO:;;COMIENZO DEL BUCLE		
		MOV AH, DS:FILA1[DI];; COMO ES SOLO 1B COGEMOS LA PARTE ALTA DEL CODIGO
		CALL TOASCII ;; LLAMAMOS A LA RUTINA
		MOV AH, 2
		MOV DL, [BX];;
		INT 21H
		ADD DI, 1
		CMP DI, CX
		JNE COMIENZO
	;;;;;;;IMPRIMIMOS LOS CORCHETES;;;;;;;;;;;;;;;;;;;
	mov AH, 2 ; Número de función = 2
	mov DL, '|' ; Se desea imprimir la letra A
	int 21h ; Interrupción software al sistema operativo
	MOV AH, 9
	MOV DX, OFFSET DS:ESPACIO
	INT 21H
	;;;;;;;COMPROBAMOS E IMPRIMIMOS EL MENSAJE DEBIDO;;;;;;;;;;;;;;;;;;;
		
	CMP CX, 16
	JNE PROCESO

;;PASAMOS A IMPRIMIR EL MENSAJE ESPECIFICO
	
	CALL DUPLICADOSFILAS
	CALL DUPLICADOSCOLUMNAS
; -- rellenar con las instrucciones solicitadas
; FIN DEL PROGRAMA
MOV AX, 4C00H
INT 21H
INICIO ENDP
	
;_______________________________________________________________ 
; SUBRUTINA PARA CALCULAR EL VALOR ASCII DE UN NUMERO 
; ENTRADA CL=NUMERO, EN AX SUPONEMOS SE ENCUENTRA
; SALIDA DX:BX=RESULTADO
;_______________________________________________________________ 
TOASCII PROC NEAR 
    ADD AH, 30H;;PASAMOS EL NUMERO A ASCII
	MOV CONVERSION, AH
	MOV BX, SEG CONVERSION
	MOV DX, BX
	MOV BX, OFFSET CONVERSION
    RET 
TOASCII ENDP 
;_______________________________________________________________ 
; SUBRUTINA PARA SABER SI HAY DUPLICADOS EN UN VECTOR
; ENTRADA 
;_______________________________________________________________ 
DUPLICADOSFILAS PROC 
	MOV SI, 0
	COMIENZOFILAS:
		MOV AH, DS:FILA1[SI];; COMO ES SOLO 1B COGEMOS LA PARTE ALTA DEL CODIGO
		CMP AH, 4			  ;; COMPARAMOS SI ES MAYOR QUE 4
		JG ERRF  
		CMP AH, 1			  ;; COMPROBAMOS SI ES MENOR QUE 1
		JL ERRF
		ADD SI, 1
		MOV AL, DS:FILA1[SI];;CARGAMOS EL SIGUIENTE NUMERO
		CMP AL, 4			 ;;COMPARAMOS SI ES MAYOR QUE 4
		JG ERRF
		CMP AL, 1			 ;; COMPROBAMOS SI ES MENOR QUE 1
		JL ERRF
		CMP AH, AL			 ;;COMPARAMOS SI SON IGUALES
		JE ERRF
		ADD SI, 1
		MOV BH, DS:FILA1[SI];;CARGAMOS EL SIGUIENTE NUMERO
		CMP BH, 4	         ;;COMPARAMOS SI ES MAYOR QUE 4
		JG ERRF
		CMP BH, 1  			 ;; COMPROBAMOS SI ES MENOR QUE 1
		JL ERRF
		CMP AH, BH			 ;;COMPROBAMOS IGUALDADES
		JE ERRF
		CMP AL, BH			 
		JE ERRF
		ADD SI, 1
		MOV BL, DS:FILA1[SI];;CARGAMOS EL SIGUIENTE NUMERO
		CMP BL, 4		     ;;COMPROBAMOS SI ES MAYOR QUE 4
		JG ERRF
		CMP BL, 1			;; COMPROBAMOS SI ES MENOR QUE 1
		JL ERRF
		CMP AH, BL			 ;;COMPROBAMOS IGUALDADES
		JE ERRF
		CMP AL, BL
		JE ERRF
		CMP BH, BL
		JNE OKF
	ERRF:
		MOV AH, 9
		MOV DX, OFFSET DS:FILASERR
		INT 21H
		RET
	OKF:
		ADD SI, 1
		CMP SI, 16
		JNE COMIENZOFILAS
		MOV AH, 9
		MOV DX, OFFSET DS:FILASOK
		INT 21H
		RET
DUPLICADOSFILAS ENDP	

DUPLICADOSCOLUMNAS PROC
	MOV DI, 0
	COMIENZOCOLUMNAS:
		MOV SI, DI
		MOV AH, DS:FILA1[SI];; COMO ES SOLO 1B COGEMOS LA PARTE ALTA DEL CODIGO
		CMP AH, 4			  ;; COMPARAMOS SI ES MAYOR QUE 4
		JG ERRC  
		CMP AH, 1			  ;; COMPROBAMOS SI ES MENOR QUE 1
		JL ERRC
		ADD SI, 4
		MOV AL, DS:FILA1[SI];;CARGAMOS EL SIGUIENTE NUMERO
		CMP AL, 4			 ;;COMPARAMOS SI ES MAYOR QUE 4
		JG ERRC
		CMP AL, 1			 ;; COMPROBAMOS SI ES MENOR QUE 1
		JL ERRC
		CMP AH, AL			 ;;COMPARAMOS SI SON IGUALES
		JE ERRC
		ADD SI, 4
		MOV BH, DS:FILA1[SI];;CARGAMOS EL SIGUIENTE NUMERO
		CMP BH, 4	         ;;COMPARAMOS SI ES MAYOR QUE 4
		JG ERRC
		CMP BH, 1  			 ;; COMPROBAMOS SI ES MENOR QUE 1
		JL ERRC
		CMP AH, BH			 ;;COMPROBAMOS IGUALDADES
		JE ERRC
		CMP AL, BH			 
		JE ERRC
		ADD SI, 4
		MOV BL, DS:FILA1[SI];;CARGAMOS EL SIGUIENTE NUMERO
		CMP BL, 4		     ;;COMPROBAMOS SI ES MAYOR QUE 4
		JG ERRC
		CMP BL, 1			;; COMPROBAMOS SI ES MENOR QUE 1
		JL ERRC
		CMP AH, BL			 ;;COMPROBAMOS IGUALDADES
		JE ERRC
		CMP AL, BL
		JE ERRC
		CMP BH, BL
		JNE OKC
	ERRC:
		MOV AH, 9
		MOV DX, OFFSET DS:COLUMNASERR
		INT 21H
		RET
	OKC:
		ADD DI, 1
		CMP DI, 4
		JNE COMIENZOCOLUMNAS
		MOV AH, 9
		MOV DX, OFFSET DS:COLUMNASOK
		INT 21H
		RET
DUPLICADOSCOLUMNAS ENDP	

CAPTURAMATRIZ PROC
	INICIOCAPTURA:
		MOV AH, 9
		MOV DX, OFFSET DS:MENSAJE
		INT 21H
	CAPTURA:;Función captura de teclado
		MOV AH,0AH    		 
		MOV DX,OFFSET DS:NUMERO      
		INT 21H
	RET
CAPTURAMATRIZ ENDP
		
		
	
; FIN DEL SEGMENTO DE CODIGO 
CODE ENDS
; FIN DEL PROGRAMA INDICANDO DONDE COMIENZA LA EJECUCION
END INICIO